# Generated by Django 4.1.2 on 2023-06-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_accountuser_like_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='like_color',
            field=models.CharField(default='ui inverted red', max_length=120),
        ),
    ]
