# Generated by Django 4.1.2 on 2023-06-12 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_accountuser_like_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountuser',
            name='color',
            field=models.CharField(default='inverted', max_length=80),
        ),
    ]
