# Generated by Django 4.1.2 on 2023-02-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentsection',
            name='c_id',
        ),
    ]
