# Generated by Django 4.1.2 on 2023-06-02 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_likesection_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likesection',
            name='totalNumberOfLikes',
        ),
        migrations.AddField(
            model_name='likesection',
            name='Likes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
