# Generated by Django 4.1.2 on 2023-06-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_likesection_totalnumberoflikes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LikeSection',
        ),
    ]
