# Generated by Django 4.1.2 on 2023-06-08 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_blogpost_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='color',
            field=models.CharField(default='red', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='text',
            field=models.CharField(default='like', max_length=50),
        ),
    ]
