# Generated by Django 4.1.2 on 2023-06-08 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_blogpost_color_blogpost_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='color',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='text',
        ),
    ]
